[package]
name = "catalyze"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "wip"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
protobuf = "3.3.0"
snafu = "0.8"
itertools = "0.12.0"
slotmap = "1.0.7"
paste = "1.0"
inherent = "1.0"
ahash = "0.8.7"
